/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart { 'items' : Array<CartItem>, 'totalPrice' : bigint }
export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export type Category = string;
export interface Inquiry {
  'id' : bigint,
  'resolved' : boolean,
  'name' : string,
  'productId' : [] | [bigint],
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface InquiryInput {
  'name' : string,
  'productId' : [] | [bigint],
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export interface ProductInput {
  'name' : string,
  'description' : string,
  'available' : boolean,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[Category], undefined>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createProduct' : ActorMethod<[ProductInput], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'filterProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCategories' : ActorMethod<[], Array<Category>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'markInquiryResolved' : ActorMethod<[bigint], undefined>,
  'removeCategory' : ActorMethod<[Category], undefined>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProductsByName' : ActorMethod<[string], Array<Product>>,
  'submitInquiry' : ActorMethod<[InquiryInput], undefined>,
  'updateProduct' : ActorMethod<[bigint, ProductInput], undefined>,
  'viewCart' : ActorMethod<[], Cart>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];